### ISSUE TITLE
webgl black screen

### ISSUE THREAD

**Issue by michaellu88** [ethereum-boilerplate/ethereum-unity-boilerplate#8]
the project possible to run in webgl?

**Comment by xactant** [comment]
@michaellu88 ,

There is an issue at this time with using WebGL.  So the short answer is not yet.

The Moralis SDK, Moralis Web3API, and Wallet Connect all use multi-threading heavily. Additionally the SDK and W.C. both use Websockets. WebGL does not support either multi-threading or web-sockets. This is due to how WASM works more the Unity.

I am currently working on a work around for both of these issues that I hope to have done in the next two weeks.

FYI Later today (12/15) I will add the feature list for the net release and will include this as "WebGL Workaround."

Regards,

David

**Comment by xactant** [comment]
Fixed as part of release 1.0.2
